# Generated by Django 5.2.6 on 2025-09-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothinglisting',
            name='category',
            field=models.CharField(choices=[('cotton', 'Cotton/Natural'), ('synthetic', 'Synthetic'), ('mixed', 'Mixed')], default='mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='clothinglisting',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
