# Generated by Django 5.2.6 on 2025-09-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_userlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothinglisting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothinglisting',
            name='eco_impact',
        ),
    ]
